# Generated by Django 4.2.15 on 2025-08-21 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complete']},
        ),
    ]
